[[bin]]
name = "pl"
path = "src/pl.rs"

[package]
name = "powerline-shell"
version = "0.0.1"
authors = [ "shosatojp <me@shosato.jp>" ]
edition = "2018"

[dependencies]
git2 = "*"
whoami = "*"
clap = "*"

[profile.dev]
opt-level = "s"
lto = true
panic = "abort"
# link-args = "-static"

[build]
jobs = 16
