[[bin]]
name = "pl"
path = "src/pl.rs"

[package]
name = "powerline-shell"
version = "0.0.1"
authors = [ "shosatojp <me@shosato.jp>" ]
edition = "2018"
repository = "https://github.com/shosatojp/powerline-shell"
license = "MIT"

[dependencies]
git2 = "*"
whoami = "*"
clap = "*"

[profile.dev]
opt-level = 3
lto = true
panic = "abort"
debug = false
codegen-units = 1
link-args = "-static"

[build]
jobs = 16
