name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  strategy:
    matrix:
      os: [ ubuntu-latest, macos-latest ]

  build:
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
